#!/usr/bin/env python

import sys

symbol_to_shape = {"%": "diamond", "&": "square"}


def generate_dot_file(input_file):
    with open(input_file) as file:
        print("digraph {")

        shape_to_names = {}

        for line in file:
            shape = symbol_to_shape.get(line[0])

            if shape is not None:
                line = line[1:]
                name = line.split(maxsplit=1)[0]
                shape_to_names.setdefault(shape, []).append(name)

            print(f"    {line.strip()}")

        for shape, names in shape_to_names.items():
            for name in names:
                print(f"    {name} [shape={shape}]")

        print("}")


def main():
    for input_file in sys.argv[1:]:
        generate_dot_file(input_file)


if __name__ == "__main__":
    main()
